version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:eu-central-1:396608771737:task-definition/my-java-app-task:latest"
        LoadBalancerInfo:
          ContainerName: "my-java-app"
          ContainerPort: 8080
        PlatformVersion: "LATEST"
        NetworkConfiguration:
          AwsvpcConfiguration:
            Subnets:
              - "subnet-0253cf3ef0d981ca4"  # Replace with PrivateSubnet1 ID
              - "subnet-0ab8d6eb90b96db29"  # Replace with PrivateSubnet2 ID
            SecurityGroups:
              - "sg-sg-0a28701054e1cba0f"
            AssignPublicIp: "DISABLED"
