AWSTemplateFormatVersion: '2010-09-09'
Description: ECS Fargate service update

Parameters:
  ECRImageUri:
    Type: String
    Default: 396608771737.dkr.ecr.eu-central-1.amazonaws.com/my-java-app:latest
  ClusterName:
    Type: String
    Default: my-ecs-cluster
  ServiceName:
    Type: String
    Default: my-java-app-service
  ExecutionRoleArn:
    Type: String
    Default: arn:aws:iam::396608771737:role/ecsTaskExecutionRole


Resources:
  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: my-java-app-task
      Cpu: 256
      Memory: 512
      NetworkMode: awsvpc
      RequiresCompatibilities: [FARGATE]
      ExecutionRoleArn: !Ref ExecutionRoleArn
      ContainerDefinitions:
        - Name: my-java-app
          Image: !Ref ECRImageUri
          PortMappings:
            - ContainerPort: 8080
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: /ecs/my-java-app
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: ecs

  ServiceUpdate:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref ClusterName
      ServiceName: !Ref ServiceName
      TaskDefinition: !Ref TaskDefinition
      DeploymentController:
        Type: CODE_DEPLOY
